(function (PL) {
  'use strict';
  const colors={analytic:'#0b6e99',numeric:'#d97706',drag:'#8b3fa0'},dashes={analytic:[],numeric:[8,4],drag:[3,4]};
  function setup(canvas){const dpr=window.devicePixelRatio||1,r=canvas.getBoundingClientRect(),w=Math.max(300,r.width),h=Math.max(180,r.height);if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr;}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);return{c,w,h};}
  function drawFrame(c,w,h,xMax,yMax,xLabel,yLabel,transform){const p={l:58,r:16,t:16,b:38},mapX=transform?transform.mapX:PL.Axis.linearScale(0,xMax,p.l,w-p.r),mapY=transform?transform.mapY:PL.Axis.linearScale(0,yMax,h-p.b,p.t),xTicks=PL.Axis.createTicks(xMax,5),yTicks=PL.Axis.createTicks(yMax,4);c.clearRect(0,0,w,h);c.fillStyle='#fff';c.fillRect(0,0,w,h);c.strokeStyle='#cbd5df';c.lineWidth=1;c.font='12px system-ui';c.fillStyle='#536170';xTicks.forEach((t,index)=>{const x=mapX(t.value);c.beginPath();c.moveTo(x,p.t);c.lineTo(x,h-p.b);c.stroke();c.textAlign=index===0?'left':(index===xTicks.length-1?'right':'center');c.fillText(t.label,x,h-p.b+18);});c.textAlign='right';yTicks.forEach(t=>{const y=mapY(t.value);c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke();c.fillText(t.label,p.l-7,y+4);});c.fillStyle='#263746';c.textAlign='center';c.fillText(xLabel,p.l+(w-p.l-p.r)/2,h-5);c.save();c.translate(13,p.t+(h-p.t-p.b)/2);c.rotate(-Math.PI/2);c.fillText(yLabel,0,0);c.restore();return Object.assign(p,{mapX,mapY});}
  function line(c,points,mapX,mapY,id){c.strokeStyle=colors[id];c.setLineDash(dashes[id]);c.lineWidth=2;c.beginPath();points.forEach((s,i)=>{const x=mapX(s),y=mapY(s);if(i)c.lineTo(x,y);else c.moveTo(x,y);});c.stroke();c.setLineDash([]);}
  function drawArrow(c,start,end){const angle=Math.atan2(end.y-start.y,end.x-start.x),head=9;c.beginPath();c.moveTo(start.x,start.y);c.lineTo(end.x,end.y);c.stroke();c.beginPath();c.moveTo(end.x,end.y);c.lineTo(end.x-head*Math.cos(angle-.45),end.y-head*Math.sin(angle-.45));c.lineTo(end.x-head*Math.cos(angle+.45),end.y-head*Math.sin(angle+.45));c.closePath();c.fill();}
  function drawInitialVector(c,snap,transform,vector){const viewSpan=Math.min(transform.xMax,transform.yMax),origin=transform.mapPoint(vector.start.x,vector.start.y),end=transform.mapPoint(vector.end.x,vector.end.y),radius=Math.min(viewSpan*.08,vector.speed*vector.scaleSeconds*.45),angle=snap.params.angleDeg*Math.PI/180,s0=vector.start;c.save();c.strokeStyle='#153d4d';c.fillStyle='#153d4d';c.lineWidth=2;c.setLineDash([]);drawArrow(c,origin,end);c.strokeStyle='#68808a';c.lineWidth=1;c.setLineDash([4,4]);const refEnd=transform.mapPoint(s0.x+Math.max(radius*1.5,viewSpan*.12),s0.y);c.beginPath();c.moveTo(origin.x,origin.y);c.lineTo(refEnd.x,refEnd.y);c.stroke();c.setLineDash([]);if(radius>0&&Math.abs(angle)>.001){c.strokeStyle='#153d4d';c.beginPath();for(let i=0;i<=24;i+=1){const a=angle*i/24,p=transform.mapPoint(s0.x+radius*Math.cos(a),s0.y+radius*Math.sin(a));if(i)c.lineTo(p.x,p.y);else c.moveTo(p.x,p.y);}c.stroke();}const label=transform.mapPoint(s0.x+radius*1.25*Math.cos(angle/2),s0.y+radius*1.25*Math.sin(angle/2));c.font='bold 12px system-ui';c.textAlign='left';c.fillText('θ = '+PL.Axis.formatTickFi(snap.params.angleDeg,1)+'°',label.x+4,label.y-4);c.restore();}
  function drawCalculationPoints(c,trajectory,mapX,mapY){c.save();c.fillStyle=colors.numeric;trajectory.samples.forEach(sample=>{c.beginPath();c.arc(mapX(sample),mapY(sample),2.7,0,Math.PI*2);c.fill();});c.restore();}
  function drawTrajectory(canvas,snap,options){const q=setup(canvas),plot={left:58,right:q.w-16,top:16,bottom:q.h-38},vector=PL.TrajectoryView.velocityVector(snap.params,PL.TrajectoryView.VELOCITY_VECTOR_SECONDS);let bounds=PL.TrajectoryView.dataBounds(snap.trajectories);if(options.showInitialVector)bounds=PL.TrajectoryView.includeVector(bounds,vector);const transform=PL.TrajectoryView.createTransform(bounds,plot,options.scaleMode),p=drawFrame(q.c,q.w,q.h,transform.xMax,transform.yMax,'x (m)','y (m)',transform),mx=s=>p.mapX(s.x),my=s=>p.mapY(s.y);Object.values(snap.trajectories).forEach(t=>line(q.c,t.samples,mx,my,t.id));if(options.showCalculationPoints)drawCalculationPoints(q.c,snap.trajectories.numeric,mx,my);if(options.showInitialVector)drawInitialVector(q.c,snap,transform,vector);Object.keys(snap.states).forEach(id=>{const s=snap.states[id];q.c.fillStyle=colors[id];q.c.beginPath();q.c.arc(mx(s),my(s),5,0,Math.PI*2);q.c.fill();});return transform;}
  function drawTime(canvas,snap,kind){const q=setup(canvas),all=Object.values(snap.trajectories),maxT=snap.duration||1,values=[];all.forEach(t=>t.samples.forEach(s=>values.push(kind==='position'?Math.max(s.x,s.y):Math.hypot(s.vx,s.vy))));const yMax=Math.max(1,...values)*1.08,p=drawFrame(q.c,q.w,q.h,maxT,yMax,'t (s)',kind==='position'?'paikka (m)':'nopeus (m/s)'),mx=s=>p.mapX(s.t),my=v=>p.mapY(v);all.forEach(t=>{if(kind==='position'){line(q.c,t.samples,mx,s=>my(s.x),t.id);q.c.globalAlpha=.55;line(q.c,t.samples,mx,s=>my(Math.max(0,s.y)),t.id);q.c.globalAlpha=1;}else line(q.c,t.samples,mx,s=>my(Math.hypot(s.vx,s.vy)),t.id);});const cursor=p.mapX(snap.time);q.c.strokeStyle='#1f2937';q.c.beginPath();q.c.moveTo(cursor,p.t);q.c.lineTo(cursor,q.h-p.b);q.c.stroke();}
  PL.Charts={drawTrajectory,drawPosition:(c,s)=>drawTime(c,s,'position'),drawVelocity:(c,s)=>drawTime(c,s,'velocity')};
}(window.ProjectileLab=window.ProjectileLab||{}));
