(function (PL) {
  'use strict';
  function setText(element,value){element.textContent=String(value==null?'':value);return element;}
  function make(tag,className,text){const element=document.createElement(tag);if(className)element.className=className;if(text!==undefined)setText(element,text);return element;}
  function formatValue(value){if(Array.isArray(value))return value.map(formatValue).join(' / ');if(typeof value!=='number')return String(value);if(!Number.isFinite(value))return'—';const magnitude=Math.abs(value),digits=magnitude===0?0:(magnitude<.0001?8:magnitude<.01?6:magnitude<1?4:3);return value.toFixed(digits).replace('.',',');}
  function init(config){const manager=PL.TaskEngine.createManager(PL.TaskData),select=document.getElementById('taskSelect'),placeholder=make('option','','Valitse tutkimustehtävä');placeholder.value='';select.appendChild(placeholder);PL.TaskData.forEach(task=>{const option=make('option','',task.title);option.value=task.id;select.appendChild(option);});
    function saveText(){const session=PL.TaskEngine.currentSession(manager);if(!session)return;session.hypothesis=document.getElementById('taskHypothesis').value;session.conclusion=document.getElementById('taskConclusion').value;}
    function renderObservations(){const task=PL.TaskEngine.currentTask(manager),session=PL.TaskEngine.currentSession(manager),head=document.getElementById('observationHead'),body=document.getElementById('observationBody');head.textContent='';body.textContent='';const row=make('tr');task.columns.forEach(label=>{const cell=make('th','',label);cell.scope='col';row.appendChild(cell);});head.appendChild(row);session.observations.forEach(observation=>{const tr=make('tr');observation.cells.forEach(value=>tr.appendChild(make('td','',formatValue(value))));body.appendChild(tr);});setText(document.getElementById('observationCount'),session.observations.length+' / '+task.minObservations+' vähimmäishavaintoa');setText(document.getElementById('taskFeedback'),PL.TaskEngine.feedback(manager));}
    function render(){const task=PL.TaskEngine.currentTask(manager),intro=document.getElementById('taskIntro'),workspace=document.getElementById('taskWorkspace');if(!task){select.value='';intro.hidden=false;workspace.hidden=true;setText(document.getElementById('taskContextNotice'),'');return;}const session=PL.TaskEngine.currentSession(manager);intro.hidden=true;workspace.hidden=false;select.value=task.id;setText(document.getElementById('taskGoal'),task.goal);setText(document.getElementById('taskInstructions'),task.instructions);setText(document.getElementById('taskContextNotice'),task.contextNotice||'');setText(document.getElementById('hypothesisPrompt'),task.hypothesisPrompt);document.getElementById('taskHypothesis').value=session.hypothesis;document.getElementById('taskConclusion').value=session.conclusion;const presets=document.getElementById('taskPresets');presets.textContent='';task.presets.forEach(preset=>{const button=make('button','preset-button',preset.label);button.type='button';button.addEventListener('click',()=>config.applyParams(preset.values));presets.appendChild(button);});setText(document.getElementById('taskHint'),session.hintIndex?task.hints[session.hintIndex-1]:'Avaa vihje tarvittaessa.');setText(document.getElementById('showHint'),PL.TaskEngine.hintButtonLabel(manager));renderObservations();}
    function activate(id){saveText();PL.TaskEngine.switchTask(manager,id);const task=PL.TaskEngine.currentTask(manager);if(task.entryValues)config.applyParams(task.entryValues);render();}
    function clearToBase(){PL.TaskEngine.clearAll(manager);render();}
    select.addEventListener('change',()=>{if(select.value)activate(select.value);else clearToBase();});document.getElementById('taskHypothesis').addEventListener('input',event=>{PL.TaskEngine.currentSession(manager).hypothesis=event.target.value;});document.getElementById('taskConclusion').addEventListener('input',event=>{PL.TaskEngine.currentSession(manager).conclusion=event.target.value;});document.getElementById('addObservation').addEventListener('click',()=>{PL.TaskEngine.addObservation(manager,config.getSnapshot());renderObservations();});document.getElementById('resetTask').addEventListener('click',()=>{const task=PL.TaskEngine.currentTask(manager);PL.TaskEngine.resetTask(manager);if(task.entryValues)config.applyParams(task.entryValues);render();});document.getElementById('showHint').addEventListener('click',event=>{setText(document.getElementById('taskHint'),PL.TaskEngine.nextHint(manager));setText(event.currentTarget,PL.TaskEngine.hintButtonLabel(manager));});render();return{manager,render,renderObservations,activate,clearToBase};}
  PL.TasksUI={init,setText,formatValue};
}(window.ProjectileLab=window.ProjectileLab||{}));
