(function (PL) {
  'use strict';
  function emptySession(){return{hypothesis:'',conclusion:'',observations:[],hintIndex:0};}
  function createManager(tasks){const sessions={};tasks.forEach(t=>sessions[t.id]=emptySession());return{tasks,currentTaskId:null,sessions};}
  function currentTask(manager){return manager.tasks.find(t=>t.id===manager.currentTaskId);}
  function currentSession(manager){return manager.currentTaskId?manager.sessions[manager.currentTaskId]:null;}
  function switchTask(manager,id){if(!manager.tasks.some(t=>t.id===id))throw new Error('Tuntematon tehtävä');if(manager.currentTaskId!==id)manager.sessions[id].hintIndex=0;manager.currentTaskId=id;return currentSession(manager);}
  function resetTask(manager,id){const taskId=id||manager.currentTaskId;if(!taskId)throw new Error('Tehtävää ei ole valittu');manager.sessions[taskId]=emptySession();return manager.sessions[taskId];}
  function clearAll(manager){manager.tasks.forEach(task=>manager.sessions[task.id]=emptySession());manager.currentTaskId=null;return manager;}
  function errorMetrics(analytic,numeric){function item(a,n){const absolute=Math.abs(n-a);return{absolute,relative:a===0?(absolute===0?0:Infinity):absolute/Math.abs(a)};}return{range:item(analytic.range,numeric.range),flightTime:item(analytic.flightTime,numeric.flightTime)};}
  function complementComparison(params){const angle=params.angleDeg,complement=90-angle,a=PL.Physics.analyticMetrics(params),b=PL.Physics.analyticMetrics(Object.assign({},params,{angleDeg:complement}));return{angle,complement,range:a.range,complementRange:b.range,difference:Math.abs(a.range-b.range)};}
  function observationFor(taskId,snapshot){const p=snapshot.params,t=snapshot.trajectories,a=t.analytic.metrics,n=t.numeric.metrics,d=t.drag.metrics;if(taskId==='angle-range'){const c=complementComparison(p);return{cells:[c.angle+'°',c.range,c.complement+'°',c.complementRange],data:c};}if(taskId==='drag-effect')return{cells:[p.dragCoefficient,[a.range,d.range],[a.maxHeight,d.maxHeight],[a.flightTime,d.flightTime],[a.impactSpeed,d.impactSpeed]],data:{k:p.dragCoefficient,analytic:a,drag:d}};if(taskId==='time-step'){const errors=errorMetrics(a,n),points=t.numeric.samples.length,steps=Math.max(0,points-1);return{cells:[p.dt,errors.range.absolute,errors.flightTime.absolute,steps,points],data:{dt:p.dt,errors,steps,points,dragCoefficient:p.dragCoefficient}};}throw new Error('Tuntematon tehtävä');}
  function addObservation(manager,snapshot){const observation=observationFor(manager.currentTaskId,snapshot);currentSession(manager).observations.push(observation);return observation;}
  function nextHint(manager){const task=currentTask(manager),session=currentSession(manager);if(!task||!session)throw new Error('Tehtävää ei ole valittu');session.hintIndex=session.hintIndex>=task.hints.length?1:session.hintIndex+1;return task.hints[session.hintIndex-1];}
  function hintButtonLabel(manager){const task=currentTask(manager),session=currentSession(manager);return task&&session&&session.hintIndex===task.hints.length?'Näytä vihjeet alusta':'Näytä seuraava vihje';}
  function feedback(manager){const task=currentTask(manager),session=currentSession(manager),count=session.observations.length;if(count<task.minObservations)return'Tee vielä '+(task.minObservations-count)+' havainto'+(task.minObservations-count===1?'':'a')+'.';if(task.id==='angle-range'){const distinct=new Set(session.observations.map(o=>o.data.angle));if(distinct.size<6)return'Havaintoja on tarpeeksi, mutta tutki vähintään kuutta eri lähtökulmaa.';const best=session.observations.reduce((a,b)=>b.data.range>a.data.range?b:a);return'Kuusi eri kulmaa on tutkittu. Suurin mitattu kantama saatiin kulmalla '+best.data.angle+'°. Vertaa nyt komplementtikulmia ja kirjoita päätelmä.';}if(task.id==='drag-effect'){const distinctPositive=new Set(session.observations.filter(o=>o.data.k>0).map(o=>o.data.k));return distinctPositive.size<3?'Havaintoja on tarpeeksi, mutta käytä vähintään kolmea eri positiivista vastuskertoimen arvoa.':'Kolme positiivista vastuskerrointa on vertailtu. Erota päätelmässä fysikaalisen mallin muutos ratkaisumenetelmän muutoksesta.';}const distinctDt=new Set(session.observations.map(o=>o.data.dt)),zeroDrag=session.observations.every(o=>o.data.dragCoefficient===0);if(!zeroDrag)return'Aseta ilmanvastus nollaksi, jotta vertaat RK4:ää samaan analyyttiseen malliin.';if(distinctDt.size<3)return'Havaintoja on tarpeeksi, mutta käytä vähintään kolmea eri aika-askelta.';const displayLevel=session.observations.every(o=>o.data.errors.range.absolute<1e-9&&o.data.errors.flightTime.absolute<1e-9);return displayLevel?'Tunnuslukujen virhe jäi näyttötarkkuuden tasolle. Tämä on hyväksyttävä havainto vakion kiihtyvyyden RK4-tapauksessa. Vertaa silti laskentapisteiden määrää ja radan kulmikkuutta; maaosuma tarkennetaan askeleen sisältä juurihakuna.':'Kolme aika-askelta on vertailtu. Tarkastele erikseen tunnuslukujen virhettä, laskentapisteiden määrää, ratakuvan näytteistystä ja maaosuman paikannusta.';}
  PL.TaskEngine={createManager,currentTask,currentSession,switchTask,resetTask,clearAll,errorMetrics,complementComparison,observationFor,addObservation,nextHint,hintButtonLabel,feedback,capabilities:{network:false,persistentStorage:false}};
}(window.ProjectileLab=window.ProjectileLab||{}));
