(function (PL) {
  'use strict';
  const $=id=>document.getElementById(id),fields=['speed','angleDeg','height','mass','gravity','dragCoefficient','dt'];
  function paramsFromValues(values){const p={};fields.forEach(key=>{const raw=values[key];if(raw===undefined||raw===null||String(raw).trim()==='')throw new Error('Täytä kaikki alkuarvot.');p[key]=Number(raw);});PL.Physics.validateParams(p);return p;}
  function params(){const values={};fields.forEach(key=>values[key]=$(key).value);return paramsFromValues(values);}
  function fmt(value,digits){return Number.isFinite(value)?value.toFixed(digits===undefined?2:digits).replace('.',','):'—';}
  function dragPresentation(k){return{legend:'Neliöllinen vastus, k='+(k===0?'0':PL.Axis.formatTickFi(k,k)),showZeroNotice:k===0,notice:'Kun k=0, neliöllisen ilmanvastuksen termi häviää ja malli palautuu vastuksettomaksi malliksi. Ratojen päällekkäisyys on odotettu tulos.'};}
  function viewOptions(){const selected=document.querySelector('input[name="scaleMode"]:checked');return{scaleMode:selected?selected.value:'true-scale',showInitialVector:$('showInitialVector').checked,showCalculationPoints:$('showCalculationPoints').checked};}
  function moment(snapshot,key){const state=snapshot.states[key],trajectory=snapshot.trajectories[key],landed=snapshot.time>=trajectory.metrics.flightTime-1e-10;return{x:state.x,y:state.y,vx:state.vx,vy:state.vy,speed:Math.hypot(state.vx,state.vy),landed,phase:landed?'Osunut maahan':'Lennossa',flightTime:trajectory.metrics.flightTime};}
  function instantaneousComparison(snapshot){return{free:moment(snapshot,'numeric'),drag:moment(snapshot,'drag'),time:snapshot.time};}
  function renderMoment(prefix,value){$(prefix+'X').textContent=fmt(value.x,2)+' m';$(prefix+'Y').textContent=fmt(value.y,2)+' m';$(prefix+'Vx').textContent=fmt(value.vx,2)+' m/s';$(prefix+'Vy').textContent=fmt(value.vy,2)+' m/s';$(prefix+'Speed').textContent=fmt(value.speed,2)+' m/s';$(prefix+'Phase').textContent=value.landed?'Osunut maahan ajassa '+fmt(value.flightTime,3)+' s':'Lennossa';$(prefix+'Phase').classList.toggle('landed',value.landed);}
  function metricRows(snapshot){const body=$('metricsBody');body.textContent='';[['analytic','Analyyttinen'],['numeric','RK4, ei vastusta'],['drag','Neliöllinen vastus']].forEach(item=>{const m=snapshot.trajectories[item[0]].metrics,tr=document.createElement('tr'),header=document.createElement('th');header.scope='row';header.textContent=item[1];tr.appendChild(header);[m.flightTime,m.maxHeight,m.range,m.impactSpeed].forEach(value=>{const cell=document.createElement('td');cell.textContent=fmt(value,3);tr.appendChild(cell);});body.appendChild(tr);});}
  function renderSummaries(snapshot,comparison){const time=fmt(snapshot.time,3),free='Vastukseton vertailumalli: '+comparison.free.phase+', x '+fmt(comparison.free.x,2)+' metriä, y '+fmt(comparison.free.y,2)+' metriä, v x '+fmt(comparison.free.vx,2)+' metriä sekunnissa ja v y '+fmt(comparison.free.vy,2)+' metriä sekunnissa.',drag='Ilmanvastusmalli: '+comparison.drag.phase+', x '+fmt(comparison.drag.x,2)+' metriä, y '+fmt(comparison.drag.y,2)+' metriä, v x '+fmt(comparison.drag.vx,2)+' metriä sekunnissa ja v y '+fmt(comparison.drag.vy,2)+' metriä sekunnissa.';$('trajectorySummary').textContent='Ratakuva ajanhetkellä '+time+' sekuntia. '+free+' '+drag;$('positionSummary').textContent='Paikkakuvaaja esittää mallien x- ja y-koordinaatit ajan funktiona. Nykyinen aika '+time+' sekuntia. '+free+' '+drag;$('velocitySummary').textContent='Nopeuskuvaaja esittää nopeuden suuruuden ajan funktiona. Nykyinen aika '+time+' sekuntia. Vastuksettoman mallin nopeus '+fmt(comparison.free.speed,2)+' metriä sekunnissa ja ilmanvastusmallin nopeus '+fmt(comparison.drag.speed,2)+' metriä sekunnissa.';}
  function render(snapshot){$('timeValue').textContent=fmt(snapshot.time,3)+' s';$('status').textContent=snapshot.running?'Käynnissä':(snapshot.time>=snapshot.duration?'Päättynyt':'Tauko / valmis');const comparison=instantaneousComparison(snapshot);renderMoment('free',comparison.free);renderMoment('drag',comparison.drag);$('play').disabled=snapshot.running||snapshot.time>=snapshot.duration;$('pause').disabled=!snapshot.running;$('step').disabled=snapshot.time>=snapshot.duration;metricRows(snapshot);const options=viewOptions(),drag=dragPresentation(snapshot.params.dragCoefficient);$('scaleWarning').hidden=options.scaleMode!=='fit';$('zeroDragNotice').hidden=!drag.showZeroNotice;$('dragLegendLabel').textContent=drag.legend;PL.Charts.drawTrajectory($('trajectory'),snapshot,options);PL.Charts.drawPosition($('positionChart'),snapshot);PL.Charts.drawVelocity($('velocityChart'),snapshot);renderSummaries(snapshot,comparison);}
  PL.UI={params,paramsFromValues,fmt,viewOptions,dragPresentation,instantaneousComparison,render,fields,$};
}(window.ProjectileLab=window.ProjectileLab||{}));
