'use strict';
const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const css=['css/styles.css','css/pedagogy.css','css/accessibility.css'].map(file=>fs.readFileSync(file,'utf8')).join('\n');
const appJs=fs.readdirSync('js').filter(file=>file.endsWith('.js')).map(file=>fs.readFileSync('js/'+file,'utf8')).join('\n');
const failures=[];
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);
if(new Set(ids).size!==ids.length)failures.push('duplicate ids');
const canvases=[...html.matchAll(/<canvas\b[^>]*>/g)].map(match=>match[0]);
if(canvases.length!==3||canvases.some(tag=>!tag.includes('role="img"')||!tag.includes('aria-label=')||!tag.includes('aria-describedby=')))failures.push('canvas roles, names or summaries');
['trajectorySummary','positionSummary','velocitySummary'].forEach(id=>{if(!html.includes('id="'+id+'"'))failures.push('missing '+id);});
const headings=[...html.matchAll(/<h([1-6])\b/g)].map(match=>Number(match[1]));
for(let index=1;index<headings.length;index+=1)if(headings[index]>headings[index-1]+1)failures.push('heading level jump');
[':focus-visible','@media(max-width:1100px)','@media(max-width:900px)','@media(max-width:650px)','min-width:0','overflow-x:auto'].forEach(token=>{if(!css.includes(token))failures.push('missing CSS '+token);});
if(/overflow-x\s*:\s*hidden/.test(css))failures.push('hidden horizontal overflow');
['taskHypothesis','taskConclusion'].forEach(id=>{if(!new RegExp('<label[^>]*for="'+id+'"').test(html))failures.push('missing label '+id);});
if((html.match(/<label class="field">/g)||[]).length!==7)failures.push('numeric field labels');
if((html.match(/<input id="(?:speed|angleDeg|height|mass|gravity|dragCoefficient|dt)"[^>]*required[^>]*aria-describedby="error"/g)||[]).length!==7)failures.push('numeric field required or error association');
if(!/<strong id="status"[^>]*role="status"[^>]*aria-live="polite"/.test(html))failures.push('simulation live status');
if(!/<p id="taskFeedback"[^>]*aria-live="polite"/.test(html))failures.push('task feedback live region');
const resourceRefs=[...html.matchAll(/(?:src|href)="([^"]+)"/g)].map(match=>match[1]);
if(resourceRefs.some(ref=>/^(?:https?:)?\/\//i.test(ref)))failures.push('external resource reference');
if(/fetch\s*\(|XMLHttpRequest|WebSocket|sendBeacon|localStorage|sessionStorage|document\.cookie/.test(appJs))failures.push('network or persistent storage API');
if(/\beval\s*\(|new\s+Function\s*\(/.test(appJs))failures.push('dynamic code execution');
if(/\.innerHTML\s*=/.test(appJs))failures.push('innerHTML assignment');
const scenarios=[[1920,1],[1366,1],[1100,1],[1000,1],[720,1],[1100,1.25],[1100,1.5]].map(([width,zoom])=>({width,zoom,cssViewport:Math.round(width/zoom),stacked:width/zoom<=900}));
console.log('STATIC A11Y/RESPONSIVE '+(failures.length?'FAIL '+failures.join(', '):'PASS'));
console.log(JSON.stringify(scenarios));
process.exitCode=failures.length?1:0;
