(function (PL) {
  'use strict';
  const results=[];
  function assertNear(actual,expected,tolerance,message){if(Math.abs(actual-expected)>tolerance)throw new Error(message+': saatiin '+actual+', odotettiin '+expected+' ± '+tolerance);}
  function assert(condition,message){if(!condition)throw new Error(message);}
  function base(overrides){return Object.assign({speed:10,angleDeg:45,height:0,mass:1,gravity:10,dragCoefficient:0,dt:.01},overrides||{});}
  function test(name,fn){try{fn();results.push({name,pass:true});}catch(error){results.push({name,pass:false,error:error.message});}}

  test('Tunnettu tapaus: kantama, lentoaika ja lakikorkeus',function(){const m=PL.Physics.analyticMetrics(base());assertNear(m.range,10,1e-12,'Kantama');assertNear(m.flightTime,Math.sqrt(2),1e-12,'Lentoaika');assertNear(m.maxHeight,2.5,1e-12,'Lakikorkeus');});
  test('Alkunopeuden komponentit muodostuvat lähtökulmasta',function(){const state=PL.Physics.initialState(base({speed:10,angleDeg:30,height:2}));assertNear(state.vx,5*Math.sqrt(3),1e-12,'Vaakakomponentti');assertNear(state.vy,5,1e-12,'Pystykomponentti');assertNear(state.y,2,1e-12,'Lähtökorkeus');});
  test('Vastuksettoman osumanopeus noudattaa energiayhteyttä',function(){const p=base({speed:17,angleDeg:23,height:8}),m=PL.Physics.analyticMetrics(p);assertNear(m.impactSpeed,Math.sqrt(p.speed*p.speed+2*p.gravity*p.height),1e-11,'Osumanopeus');});
  test('RK4 vastuksetta vastaa tunnettua tapausta',function(){const m=PL.Integrator.simulate(base(),'none').metrics;assertNear(m.range,10,1e-9,'Kantama');assertNear(m.flightTime,Math.sqrt(2),1e-9,'Lentoaika');assertNear(m.maxHeight,2.5,1e-9,'Lakikorkeus');});
  test('Vapaa pudotus levosta',function(){const p=base({speed:0,height:20}),a=PL.Physics.analyticMetrics(p),n=PL.Integrator.simulate(p,'none').metrics;assertNear(a.flightTime,2,1e-12,'Analyyttinen putoamisaika');assertNear(n.flightTime,2,1e-9,'Numeerinen putoamisaika');});
  test('Vaakasuora heitto: vx vakio ja x lineaarinen',function(){const p=base({angleDeg:0,height:5}),t=PL.Integrator.simulate(p,'none'),last=t.samples[t.samples.length-1];assertNear(last.vx,10,1e-12,'vx');assertNear(last.x,10*last.t,1e-10,'x(t)');});
  test('Pystysuora heitto: x pysyy nollassa',function(){const t=PL.Integrator.simulate(base({angleDeg:90}),'none');assert(Math.max.apply(null,t.samples.map(s=>Math.abs(s.x)))<1e-12,'x ei pysynyt nollassa');});
  test('Komplementtikulmat 30° ja 60°',function(){const a=PL.Physics.analyticMetrics(base({angleDeg:30})),b=PL.Physics.analyticMetrics(base({angleDeg:60}));assertNear(a.range,b.range,1e-12,'Kantamat');});
  test('Massa ei vaikuta vastuksettomaan rataan',function(){const a=PL.Integrator.simulate(base({mass:.1}),'none').metrics,b=PL.Integrator.simulate(base({mass:100}),'none').metrics;assertNear(a.range,b.range,1e-12,'Kantamat');});
  test('Neliöllinen vastusvoima vastustaa liikettä',function(){const p=base({dragCoefficient:.1}),s={vx:3,vy:4},a=PL.Physics.acceleration(p,s,'quadratic');const dragDot=3*a.ax+4*(a.ay+p.gravity);assert(dragDot<=0,'Vastuksen pistetulo oli positiivinen');});
  test('Neliöllisen vastuksen kiihtyvyys käyttää kerrointa k/m',function(){const p=base({mass:4,dragCoefficient:2,gravity:10}),a=PL.Physics.acceleration(p,{vx:3,vy:4},'quadratic');assertNear(a.ax,-7.5,1e-12,'Vastuksen x-kiihtyvyys');assertNear(a.ay,-20,1e-12,'Kokonaiskiihtyvyys y-suunnassa');});
  test('Nollavastus vastaa vastuksetonta RK4-mallia',function(){const p=base(),a=PL.Integrator.simulate(p,'none'),b=PL.Integrator.simulate(p,'quadratic');assertNear(a.metrics.range,b.metrics.range,1e-12,'Kantamat');assertNear(a.metrics.flightTime,b.metrics.flightTime,1e-12,'Lentoajat');assert(a.samples.length===b.samples.length,'Laskentapisteiden määrä erosi');a.samples.forEach((sample,index)=>{assertNear(sample.x,b.samples[index].x,1e-12,'Radan x pisteessä '+index);assertNear(sample.y,b.samples[index].y,1e-12,'Radan y pisteessä '+index);});});
  test('Maaosuma paikannetaan aika-askeleen sisältä',function(){const t=PL.Integrator.simulate(base({dt:.2}),'none'),last=t.samples[t.samples.length-1];assertNear(last.y,0,1e-14,'Osumakorkeus');assertNear(last.t,Math.sqrt(2),1e-9,'Osumisaika');});
  test('Neliöllinen vastus pienentää kantamaa',function(){const p=base({dragCoefficient:.05}),free=PL.Integrator.simulate(p,'none').metrics,drag=PL.Integrator.simulate(p,'quadratic').metrics;assert(drag.range<free.range,'Vastus ei pienentänyt kantamaa');});
  test('Suurempi massa pienentää saman vastuskertoimen vaikutusta',function(){const light=PL.Integrator.simulate(base({mass:.5,dragCoefficient:.05}),'quadratic').metrics,heavy=PL.Integrator.simulate(base({mass:2,dragCoefficient:.05}),'quadratic').metrics;assert(light.range<heavy.range,'Massan vaikutus vastuskiihtyvyyteen oli väärä');});
  test('Alaspäin suunnattu heitto lähtökorkeudelta osuu maahan johdonmukaisesti',function(){const p=base({angleDeg:-45,height:10,dt:.05}),a=PL.Physics.analyticMetrics(p),n=PL.Integrator.simulate(p,'none').metrics;assert(a.flightTime>0,'Analyyttinen lentoaika ei ollut positiivinen');assertNear(n.flightTime,a.flightTime,1e-9,'Lentoaika');assertNear(n.range,a.range,1e-9,'Kantama');assertNear(n.maxHeight,10,1e-10,'Lakikorkeus');});
  test('RK4:n vastukseton ratkaisu säilyy tarkkana aika-askeleen ääriarvoilla',function(){[.001,.5].forEach(dt=>{const p=base({dt:dt}),a=PL.Physics.analyticMetrics(p),n=PL.Integrator.simulate(p,'none').metrics;assertNear(n.range,a.range,1e-8,'Kantama, dt='+dt);assertNear(n.flightTime,a.flightTime,1e-8,'Lentoaika, dt='+dt);});});
  test('Epäkelvot ja sallitun alueen ylittävät parametrit hylätään',function(){[{angleDeg:NaN},{speed:201},{angleDeg:-90},{height:-1},{mass:0},{gravity:0},{dragCoefficient:-.1},{dt:.501}].forEach(overrides=>{let threw=false;try{PL.Physics.validateParams(base(overrides));}catch(error){threw=true;}assert(threw,'Parametreja ei hylätty: '+JSON.stringify(overrides));});});
  test('Tyhjä käyttöliittymäarvo ei muutu hiljaisesti nollaksi',function(){const values={speed:'',angleDeg:'45',height:'0',mass:'1',gravity:'9.81',dragCoefficient:'0.02',dt:'0.01'};let threw=false;try{PL.UI.paramsFromValues(values);}catch(error){threw=/Täytä kaikki/.test(error.message);}assert(threw,'Tyhjää arvoa ei hylätty');});
  test('Liian suuri näytemäärä pysäytetään ennen pitkää silmukkaa',function(){let threw=false;try{PL.Physics.createAnalyticTrajectory(base({speed:200,height:1000,gravity:.1,dt:.001}));}catch(error){threw=/liian monta pistettä/.test(error.message);}assert(threw,'Liian suurta näytemäärää ei pysäytetty');});
  test('Epävakaa RK4-laskenta pysäytetään NaN-tulosten sijasta',function(){let threw=false;try{PL.Integrator.simulate(base({speed:200,mass:.001,dragCoefficient:10,dt:.5}),'quadratic');}catch(error){threw=/epävakaaksi/.test(error.message);}assert(threw,'Epävakaata laskentaa ei pysäytetty');});
  test('Välitön maaosuma ei käynnistä tarpeetonta vastuslaskentaa',function(){const p=base({speed:0,height:0,mass:.001,dragCoefficient:10,dt:.5}),trajectory=PL.Integrator.simulate(p,'quadratic');assert(trajectory.samples.length===1,'Välitön maaosuma loi ylimääräisiä pisteitä');assertNear(trajectory.metrics.flightTime,0,1e-15,'Välitön lentoaika');});
  test('Epäonnistunut nollaus ei jätä simulaatio-ohjainta osittaiseen tilaan',function(){const controller=new PL.Simulation.Controller(null),valid=base();controller.reset(valid);const before=controller.snapshot(),invalid=base({dt:0});let threw=false;try{controller.reset(invalid);}catch(error){threw=true;}const after=controller.snapshot();assert(threw,'Virheellinen nollaus ei epäonnistunut');assert(after.params.dt===before.params.dt,'Virheellinen parametri jäi ohjaimeen');assertNear(after.trajectories.numeric.metrics.range,before.trajectories.numeric.metrics.range,1e-12,'Vanha toimiva rata ei säilynyt');});

  test('Akselimerkinnät käyttävät askelvälin tarkkuutta',function(){const cases=[[2.5,'2,5'],[1,'1'],[.5,'0,5'],[.1,'0,1'],[.000025,'0,000025']];cases.forEach(function(item){assert(PL.Axis.formatTickFi(item[0],item[0])===item[1],'Askel '+item[0]+' muotoiltiin väärin');});});
  test('2,5 välin asteikko säilyttää puolikkaat',function(){const labels=PL.Axis.createTicks(10,4).map(t=>t.label).join('|');assert(labels==='0,0|2,5|5,0|7,5|10,0','Tick-tekstit olivat '+labels);});
  test('Lineaarinen skaala sijoittaa maan ja lähtökorkeuden oikein',function(){const scale=PL.Axis.linearScale(0,10,262,16);assertNear(scale(0),262,1e-12,'Maanpinta');assertNear(scale(2),212.8,1e-12,'Lähtökorkeus 2 m');assertNear(scale(10),16,1e-12,'Yläraja');});
  test('Sama fysiikkakoordinaatti muuntuu kuvaajissa johdonmukaisesti',function(){const scales=[PL.Axis.linearScale(0,10,262,16),PL.Axis.linearScale(0,10,262,16),PL.Axis.linearScale(0,10,262,16)];[0,1,2,2.5,10].forEach(function(value){assertNear(scales[0](value),scales[1](value),1e-12,'Koordinaatti '+value);assertNear(scales[1](value),scales[2](value),1e-12,'Koordinaatti '+value);});});
  test('Lähtöpiste säilyttää valitut lähtökorkeudet',function(){[0,1,2,2.5,10,50].forEach(function(height){const p=base({height:height}),models=[PL.Physics.createAnalyticTrajectory(p),PL.Integrator.simulate(p,'none'),PL.Integrator.simulate(p,'quadratic')];models.forEach(function(t){assertNear(t.samples[0].y,height,1e-12,'Lähtökorkeus '+height+' mallissa '+t.id);});});});
  test('Negatiivinen lähtökulma käyttää yhteistä asteikkoa',function(){const p=base({height:2,angleDeg:-30,dragCoefficient:.05}),models=[PL.Physics.createAnalyticTrajectory(p),PL.Integrator.simulate(p,'none'),PL.Integrator.simulate(p,'quadratic')],yMax=Math.max(1,...models.map(t=>t.metrics.maxHeight))*1.12,scale=PL.Axis.linearScale(0,yMax,262,16);models.forEach(function(t){assertNear(t.samples[0].y,2,1e-12,'Lähtöpiste');assertNear(t.samples[t.samples.length-1].y,0,1e-12,'Maaosuma');assertNear(scale(t.samples[0].y),scale(2),1e-12,'Yhteinen asteikko');});});

  test('Oikea mittakaava käyttää samaa pikselimäärää metriä kohti',function(){const transform=PL.TrajectoryView.createTransform({xMax:100,yMax:30},{left:58,right:784,top:16,bottom:262},'true-scale');assertNear(transform.pixelsPerMeterX,transform.pixelsPerMeterY,1e-12,'Pikseliä/metri');});
  test('Sovitustila saa käyttää eri akselimittakaavoja',function(){const transform=PL.TrajectoryView.createTransform({xMax:100,yMax:30},{left:58,right:784,top:16,bottom:262},'fit');assert(Math.abs(transform.pixelsPerMeterX-transform.pixelsPerMeterY)>1e-6,'Akselit eivät skaalautuneet erikseen');});
  test('Näyttötilan vaihto ei muuta fysiikkatuloksia',function(){const p=base({height:2,angleDeg:80,dragCoefficient:.05}),trajectory=PL.Integrator.simulate(p,'quadratic'),before=JSON.stringify(trajectory.metrics),bounds=PL.TrajectoryView.dataBounds({drag:trajectory});PL.TrajectoryView.createTransform(bounds,{left:58,right:784,top:16,bottom:262},'true-scale');PL.TrajectoryView.createTransform(bounds,{left:58,right:784,top:16,bottom:262},'fit');assert(JSON.stringify(trajectory.metrics)===before,'Fysiikkatulokset muuttuivat');});
  test('Ratakuvan muunnos toimii testikulmilla ja lähtökorkeuksilla',function(){[0,10,45,80,90].forEach(function(angle){[0,1,2,2.5,10,50].forEach(function(height){const p=base({angleDeg:angle,height:height}),a=PL.Physics.createAnalyticTrajectory(p),n=PL.Integrator.simulate(p,'none'),d=PL.Integrator.simulate(p,'quadratic'),all={analytic:a,numeric:n,drag:d},bounds=PL.TrajectoryView.dataBounds(all),transform=PL.TrajectoryView.createTransform(bounds,{left:58,right:784,top:16,bottom:262},'true-scale');Object.values(all).forEach(function(t){const start=transform.mapPoint(t.samples[0].x,t.samples[0].y),ground=transform.mapPoint(t.samples[t.samples.length-1].x,0);assert(Number.isFinite(start.x)&&Number.isFinite(start.y),'Lähtöpiste ei ollut äärellinen');assertNear(ground.y,262,1e-9,'Maanpinta');});});});});
  test('Kaikki mallit käyttävät samaa ratakuvamuunnosta',function(){const p=base({height:3,angleDeg:80,dragCoefficient:.1}),models=[PL.Physics.createAnalyticTrajectory(p),PL.Integrator.simulate(p,'none'),PL.Integrator.simulate(p,'quadratic')],bounds=PL.TrajectoryView.dataBounds({a:models[0],n:models[1],d:models[2]}),transform=PL.TrajectoryView.createTransform(bounds,{left:58,right:784,top:16,bottom:262},'true-scale'),points=models.map(t=>transform.mapPoint(t.samples[0].x,t.samples[0].y));points.slice(1).forEach(point=>{assertNear(point.x,points[0].x,1e-12,'Mallien x');assertNear(point.y,points[0].y,1e-12,'Mallien y');});});
  test('Alkunopeusvektori käyttää fysiikkakomponentteja ja yhteistä muunnosta',function(){const p=base({speed:20,angleDeg:80,height:2}),vector=PL.TrajectoryView.velocityVector(p),bounds=PL.TrajectoryView.includeVector({xMax:10,yMax:10},vector),transform=PL.TrajectoryView.createTransform(bounds,{left:58,right:784,top:16,bottom:262},'true-scale'),start=transform.mapPoint(vector.start.x,vector.start.y),end=transform.mapPoint(vector.end.x,vector.end.y),visualAngle=Math.atan2(start.y-end.y,end.x-start.x)*180/Math.PI;assertNear(vector.end.x-vector.start.x,20*Math.cos(80*Math.PI/180)*.25,1e-12,'Vektorin x-komponentti');assertNear(vector.end.y-vector.start.y,20*Math.sin(80*Math.PI/180)*.25,1e-12,'Vektorin y-komponentti');assertNear(visualAngle,80,1e-10,'Vektorin visuaalinen kulma');});

  function snapshotFor(p){return{params:p,trajectories:{analytic:PL.Physics.createAnalyticTrajectory(p),numeric:PL.Integrator.simulate(p,'none'),drag:PL.Integrator.simulate(p,'quadratic')}};}
  test('Kaikki kolme tutkimustehtävää latautuvat',function(){assert(PL.TaskData.length===3,'Tehtäviä ei ollut kolme');assert(PL.TaskData.map(t=>t.id).join('|')==='angle-range|drag-effect|time-step','Tehtävät olivat väärät');});
  test('Jokaisella tutkimustehtävällä on täsmälleen kolme vihjettä',function(){PL.TaskData.forEach(task=>assert(task.hints.length===3,task.id+' sisälsi '+task.hints.length+' vihjettä'));});
  test('Vihjeet näytetään määritellyssä järjestyksessä yksi kerrallaan',function(){PL.TaskData.forEach(task=>{const manager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(manager,task.id);task.hints.forEach((expected,index)=>{assert(PL.TaskEngine.nextHint(manager)===expected,task.id+' vihje '+(index+1)+' oli väärässä järjestyksessä');assert(PL.TaskEngine.currentSession(manager).hintIndex===index+1,task.id+' vihjeindeksi oli väärä');});});});
  test('Vihjepainikkeen teksti vaihtuu kolmannen vihjeen jälkeen',function(){const manager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(manager,'angle-range');assert(PL.TaskEngine.hintButtonLabel(manager)==='Näytä seuraava vihje','Alkutilan painiketeksti oli väärä');PL.TaskEngine.nextHint(manager);PL.TaskEngine.nextHint(manager);assert(PL.TaskEngine.hintButtonLabel(manager)==='Näytä seuraava vihje','Painiketeksti vaihtui liian aikaisin');PL.TaskEngine.nextHint(manager);assert(PL.TaskEngine.hintButtonLabel(manager)==='Näytä vihjeet alusta','Kolmannen vihjeen painiketeksti oli väärä');});
  test('Vihjesarja voidaan aloittaa uudelleen ensimmäisestä vihjeestä',function(){const manager=PL.TaskEngine.createManager(PL.TaskData),task=PL.TaskData[0];PL.TaskEngine.switchTask(manager,task.id);task.hints.forEach(()=>PL.TaskEngine.nextHint(manager));assert(PL.TaskEngine.nextHint(manager)===task.hints[0],'Vihjesarja ei alkanut uudelleen ensimmäisestä');assert(PL.TaskEngine.hintButtonLabel(manager)==='Näytä seuraava vihje','Painiketeksti ei palautunut uudelleenaloituksessa');});
  test('Tehtävän vaihtaminen nollaa vihjeiden etenemisen',function(){const manager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(manager,'angle-range');PL.TaskEngine.nextHint(manager);PL.TaskEngine.nextHint(manager);PL.TaskEngine.switchTask(manager,'drag-effect');PL.TaskEngine.nextHint(manager);PL.TaskEngine.switchTask(manager,'angle-range');assert(PL.TaskEngine.currentSession(manager).hintIndex===0,'Palatun tehtävän vihjeet eivät nollautuneet');assert(PL.TaskEngine.hintButtonLabel(manager)==='Näytä seuraava vihje','Painiketeksti ei palautunut alkutilaan');assert(PL.TaskEngine.nextHint(manager)===PL.TaskData[0].hints[0],'Palattu tehtävä ei alkanut ensimmäisestä vihjeestä');});
  test('Tehtävän nollaus palauttaa ensimmäisen vihjeen tilan',function(){const manager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(manager,'time-step');PL.TaskEngine.nextHint(manager);PL.TaskEngine.nextHint(manager);PL.TaskEngine.resetTask(manager);assert(PL.TaskEngine.currentSession(manager).hintIndex===0,'Vihjeindeksi ei nollautunut');assert(PL.TaskEngine.hintButtonLabel(manager)==='Näytä seuraava vihje','Painiketeksti ei palautunut alkutilaan');assert(PL.TaskEngine.nextHint(manager)===PL.TaskData[2].hints[0],'Ensimmäinen vihje ei palautunut');});
  test('Vihjeteksti käsitellään turvallisesti tekstinä',function(){const payload='<img src=x onerror="window.hintHacked=true">',tasks=[{id:'safe-hint',hints:[payload,'toinen','kolmas']}],manager=PL.TaskEngine.createManager(tasks);PL.TaskEngine.switchTask(manager,'safe-hint');let text='';const element=new Proxy({},{set:function(target,key,value){if(key==='innerHTML')throw new Error('innerHTML-asetus');if(key==='textContent')text=value;target[key]=value;return true;}});PL.TasksUI.setText(element,PL.TaskEngine.nextHint(manager));assert(text===payload,'Vihjetekstiä muutettiin tai sitä ei asetettu textContentiin');assert(!window.hintHacked,'Vihjeen HTML suoritettiin');});
  test('Tehtävän vaihtaminen vaihtaa aktiivisen istunnon',function(){const manager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(manager,'angle-range');PL.TaskEngine.currentSession(manager).hypothesis='kulmahypoteesi';PL.TaskEngine.switchTask(manager,'drag-effect');assert(PL.TaskEngine.currentTask(manager).id==='drag-effect','Tehtävä ei vaihtunut');assert(PL.TaskEngine.currentSession(manager).hypothesis==='','Uusi istunto ei ollut tyhjä');PL.TaskEngine.switchTask(manager,'angle-range');assert(PL.TaskEngine.currentSession(manager).hypothesis==='kulmahypoteesi','Istuntoteksti ei säilynyt');});
  test('Havainnon lisääminen tallentaa nykyisen kokeen',function(){const manager=PL.TaskEngine.createManager(PL.TaskData),p=base({angleDeg:30});PL.TaskEngine.switchTask(manager,'angle-range');const observation=PL.TaskEngine.addObservation(manager,snapshotFor(p));assert(PL.TaskEngine.currentSession(manager).observations.length===1,'Havaintoa ei lisätty');assertNear(observation.data.angle,30,1e-12,'Havaintokulma');});
  test('Tehtävän nollaus tyhjentää vain aktiivisen tehtävän',function(){const manager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(manager,'angle-range');PL.TaskEngine.currentSession(manager).hypothesis='testi';PL.TaskEngine.currentSession(manager).observations.push({});PL.TaskEngine.resetTask(manager);assert(manager.currentTaskId==='angle-range','Tehtävävalinta poistui');assert(PL.TaskEngine.currentSession(manager).hypothesis===''&&PL.TaskEngine.currentSession(manager).observations.length===0,'Tehtävä ei nollautunut');});
  test('Virhemittari laskee absoluuttisen ja suhteellisen virheen',function(){const errors=PL.TaskEngine.errorMetrics({range:10,flightTime:2},{range:9.5,flightTime:2.1});assertNear(errors.range.absolute,.5,1e-12,'Kantaman absoluuttinen virhe');assertNear(errors.range.relative,.05,1e-12,'Kantaman suhteellinen virhe');assertNear(errors.flightTime.absolute,.1,1e-12,'Lentoajan absoluuttinen virhe');});
  test('Komplementtikulmien vertailu tunnistaa saman kantaman',function(){const comparison=PL.TaskEngine.complementComparison(base({angleDeg:30,height:0}));assertNear(comparison.complement,60,1e-12,'Komplementti');assertNear(comparison.range,comparison.complementRange,1e-10,'Komplementtikulmien kantamat');});
  test('Oppilaan teksti käsitellään tekstinä ilman HTML-suoritusta',function(){let text='';const element=new Proxy({},{set:function(target,key,value){if(key==='innerHTML')throw new Error('innerHTML-asetus');if(key==='textContent')text=value;target[key]=value;return true;}}),payload='<img src=x onerror="window.hacked=true">';PL.TasksUI.setText(element,payload);assert(text===payload,'Tekstiä muutettiin tai sitä ei asetettu textContentiin');assert(!window.hacked,'HTML suoritettiin');});
  test('Tehtäväjärjestelmä ei sisällä verkkoa tai pysyvää tallennusta',function(){const source=[PL.TaskEngine.createManager,PL.TaskEngine.addObservation,PL.TasksUI.init].map(fn=>fn.toString()).join(' ');assert(!/fetch|XMLHttpRequest|localStorage|sessionStorage|document\.cookie|sendBeacon/.test(source),'Kielletty verkko- tai tallennusrajapinta löytyi');assert(PL.TaskEngine.capabilities.network===false&&PL.TaskEngine.capabilities.persistentStorage===false,'Ominaisuuslupaus oli väärä');});
  test('Palaute vaatii eri kulmia ja eri aika-askelia',function(){const angleManager=PL.TaskEngine.createManager(PL.TaskData),sameAngle=snapshotFor(base({angleDeg:30}));PL.TaskEngine.switchTask(angleManager,'angle-range');for(let i=0;i<6;i+=1)PL.TaskEngine.addObservation(angleManager,sameAngle);assert(/kuutta eri/.test(PL.TaskEngine.feedback(angleManager)),'Samat kulmat hyväksyttiin');const stepManager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(stepManager,'time-step');const sameStep=snapshotFor(base({dt:.01,dragCoefficient:0}));for(let i=0;i<3;i+=1)PL.TaskEngine.addObservation(stepManager,sameStep);assert(/kolmea eri aika-askelta/.test(PL.TaskEngine.feedback(stepManager)),'Samat aika-askeleet hyväksyttiin');});
  test('Ilmanvastustehtävän ehdotukset ovat positiivisia ja näkyviä',function(){const task=PL.TaskData.find(t=>t.id==='drag-effect'),values=task.presets.map(p=>p.values.dragCoefficient);assert(task.entryValues.dragCoefficient===.02,'Tehtävän oletus ei ollut 0,02');assert(values.length>=3&&values.every(value=>value>0),'Kaikki ehdotukset eivät olleet positiivisia');assert(values.includes(.005)&&values.includes(.02)&&values.includes(.05),'Pyydetyt vastuskertoimet puuttuivat');values.forEach(value=>{const p=base({dragCoefficient:value}),free=PL.Integrator.simulate(p,'none').metrics,drag=PL.Integrator.simulate(p,'quadratic').metrics;assert(drag.range<free.range,'Rataero ei näkynyt arvolla '+value);});});
  test('Aika-askeltehtävän ehdotukset ja havaintomittarit ovat oikein',function(){const task=PL.TaskData.find(t=>t.id==='time-step'),values=task.presets.map(p=>p.values.dt);assert(values.join('|')==='0.5|0.2|0.05|0.01','Aika-askeleet olivat '+values.join('|'));assert(task.entryValues.dragCoefficient===0&&task.entryValues.showCalculationPoints===true,'Tehtävän aloitusasetukset olivat väärät');const observation=PL.TaskEngine.observationFor('time-step',snapshotFor(base({dt:.5,dragCoefficient:0})));assert(observation.cells.length===5,'Havaintomittareita ei ollut viittä');assert(observation.data.points===observation.data.steps+1,'Pisteiden ja askelten suhde oli väärä');});
  test('Aika-askelpalaute hyväksyy näyttötarkkuuden tasolle jäävän virheen',function(){const manager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(manager,'time-step');[.5,.2,.05].forEach(dt=>PL.TaskEngine.addObservation(manager,snapshotFor(base({dt:dt,dragCoefficient:0}))));assert(/hyväksyttävä havainto/.test(PL.TaskEngine.feedback(manager)),'Pientä virhettä ei hyväksytty');});
  test('Käyttöliittymä näyttää k=0-päällekkäisyysilmoituksen',function(){const zero=PL.UI.dragPresentation(0),positive=PL.UI.dragPresentation(.02);assert(zero.showZeroNotice===true,'k=0-ilmoitus ei aktivoitunut');assert(/päällekkäisyys/.test(zero.notice),'Ilmoitus ei selittänyt päällekkäisyyttä');assert(zero.legend==='Neliöllinen vastus, k=0','k=0-legenda oli '+zero.legend);assert(positive.showZeroNotice===false,'Ilmoitus näkyi positiivisella k:lla');assert(/k=0,02/.test(positive.legend),'Positiivinen kerroin puuttui legendasta');});
  test('Tehtävämoottori käynnistyy ilman aktiivista tehtävää',function(){const manager=PL.TaskEngine.createManager(PL.TaskData);assert(manager.currentTaskId===null,'Tehtävä oli aktiivinen käynnistyksessä');assert(PL.TaskEngine.currentTask(manager)===undefined,'Nykyinen tehtävä ei ollut tyhjä');});
  test('Kaikki tehtävät määrittävät oikeat aloitusasetukset',function(){const angle=PL.TaskData.find(t=>t.id==='angle-range'),drag=PL.TaskData.find(t=>t.id==='drag-effect'),step=PL.TaskData.find(t=>t.id==='time-step');assert(angle.entryValues.dragCoefficient===0,'Tehtävä 1 ei käyttänyt k=0');assert(drag.entryValues.dragCoefficient===.02,'Tehtävä 2 ei käyttänyt k=0,02');assert(step.entryValues.dragCoefficient===0,'Tehtävä 3 ei käyttänyt k=0');});
  test('Perusnäkymään palautus poistaa aktiivisen tehtävän ja istunnot',function(){const manager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(manager,'angle-range');PL.TaskEngine.currentSession(manager).observations.push({});PL.TaskEngine.clearAll(manager);assert(manager.currentTaskId===null,'Aktiivinen tehtävä jäi voimaan');assert(Object.values(manager.sessions).every(session=>session.observations.length===0&&session.hypothesis===''&&session.conclusion===''),'Istuntotietoja jäi voimaan');});
  test('Tehtävän vaihto ei näytä edellisen tehtävän havaintoja',function(){const manager=PL.TaskEngine.createManager(PL.TaskData);PL.TaskEngine.switchTask(manager,'angle-range');PL.TaskEngine.currentSession(manager).observations.push({angle:30});PL.TaskEngine.switchTask(manager,'drag-effect');assert(PL.TaskEngine.currentSession(manager).observations.length===0,'Edellisen tehtävän havainnot jäivät aktiivisiksi');});
  function timedSnapshot(p,time){const trajectories={analytic:PL.Physics.createAnalyticTrajectory(p),numeric:PL.Integrator.simulate(p,'none'),drag:PL.Integrator.simulate(p,'quadratic')},states={};Object.keys(trajectories).forEach(key=>states[key]=PL.Physics.interpolate(trajectories[key].samples,time));return{params:p,time,duration:Math.max(...Object.values(trajectories).map(t=>t.metrics.flightTime)),running:false,trajectories,states};}
  test('Molempien mallien hetkelliset arvot muodostuvat samalle ajalle',function(){const snapshot=timedSnapshot(base({dragCoefficient:.05}),.4),values=PL.UI.instantaneousComparison(snapshot);assert(values.time===.4,'Vertailuaika oli väärä');['free','drag'].forEach(key=>['x','y','vx','vy','speed'].forEach(field=>assert(Number.isFinite(values[key][field]),key+' '+field+' puuttui')));});
  test('Hetkelliset arvot päivittyvät simulaation edetessä',function(){const p=base({dragCoefficient:.05}),start=PL.UI.instantaneousComparison(timedSnapshot(p,0)),later=PL.UI.instantaneousComparison(timedSnapshot(p,.5));assert(later.free.x>start.free.x&&later.drag.x>start.drag.x,'Paikat eivät päivittyneet');assert(later.free.vy<start.free.vy&&later.drag.vy<start.drag.vy,'Pystynopeudet eivät päivittyneet');});
  test('Vastuksettoman mallin vx pysyy vakiona',function(){const p=base({dragCoefficient:0}),start=PL.UI.instantaneousComparison(timedSnapshot(p,0)),later=PL.UI.instantaneousComparison(timedSnapshot(p,.8));assertNear(start.free.vx,later.free.vx,1e-12,'Vastuksettoman mallin vx');});
  test('Ilmanvastusmallin vx poikkeaa, kun k on positiivinen',function(){const values=PL.UI.instantaneousComparison(timedSnapshot(base({dragCoefficient:.1}),.8));assert(Math.abs(values.drag.vx-values.free.vx)>1e-3,'Vaakanopeuksissa ei ollut eroa');assert(Math.abs(values.drag.vx)<Math.abs(values.free.vx),'Ilmanvastus ei pienentänyt vaakanopeutta');});
  test('Eri lentovaiheessa olevat mallit merkitään selvästi',function(){const p=base({dragCoefficient:.1}),probe=timedSnapshot(p,0),freeTime=probe.trajectories.numeric.metrics.flightTime,dragTime=probe.trajectories.drag.metrics.flightTime;assert(Math.abs(freeTime-dragTime)>1e-6,'Lentoajat eivät eronneet testitapauksessa');const values=PL.UI.instantaneousComparison(timedSnapshot(p,(freeTime+dragTime)/2));assert(values.free.landed!==values.drag.landed,'Malleja ei erotettu eri lentovaiheisiin');assert((values.free.landed?values.free.phase:values.drag.phase)==='Osunut maahan','Maahan osunutta mallia ei nimetty');});

  const list=document.getElementById('results');results.forEach(r=>{const li=document.createElement('li');li.className=r.pass?'pass':'fail';li.textContent=(r.pass?'HYVÄKSYTTY — ':'HYLÄTTY — ')+r.name+(r.error?' — '+r.error:'');list.appendChild(li);});const failed=results.filter(r=>!r.pass).length;document.getElementById('summary').textContent=(results.length-failed)+' / '+results.length+' testiä hyväksytty';document.body.dataset.testStatus=failed?'failed':'passed';window.testResults=results;
}(window.ProjectileLab=window.ProjectileLab||{}));
